services:
  db:
    image: postgres:16-alpine
    container_name: vini-movies-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123@change
      POSTGRES_DB: vini_movies
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
